In [1]:
import torch

/root/miniconda3/envs/transformer_tasks/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
# 测试torch.gather使用

In [4]:
a = torch.randn(2,5,6)  #2个句子5个token，词表大小为6
a

tensor([[[ 0.1770,  1.1301,  0.9511, -1.4429,  0.6314,  1.5918],
         [-0.5442, -0.6769,  0.1427,  1.1448, -0.4400,  0.3438],
         [ 0.0423, -0.2684,  0.6998,  0.6915,  1.4652,  0.3278],
         [ 1.2702,  0.0226, -0.5451, -0.8756, -1.6094,  0.8852],
         [ 0.6489,  0.4245,  1.1962, -0.3478, -0.0127, -0.5203]],

        [[-2.3077, -1.0497, -0.4176,  0.6287,  1.1691, -0.0733],
         [-1.5580,  2.3803, -0.1161,  1.6419,  0.7461,  0.3381],
         [ 0.3962, -0.4717,  0.2906,  1.7679,  0.6319, -1.2311],
         [-1.2353, -0.9418, -0.8874,  0.2305,  0.8811, -0.5424],
         [-1.3844, -1.1737, -0.0896, -0.3576, -0.5700, -0.2836]]])

In [8]:
b = [
    [0,2,4,1,3],
    [3,3,2,0,1]
]
b = torch.tensor(b)
# b.unsqueeze(2)
b

tensor([[0, 2, 4, 1, 3],
        [3, 3, 2, 0, 1]])

In [11]:
torch.gather(a, 2, b.unsqueeze(2)).squeeze(-1)

tensor([[ 0.1770,  0.1427,  1.4652,  0.0226, -0.3478],
        [ 0.6287,  1.6419,  0.2906, -1.2353, -1.1737]])

In [28]:
import torch

x = torch.tensor([1., 2., 3.], requires_grad=True)

# 求reduced max
y = torch.max(x)  
y.backward()
print(x.grad)  
# tensor([1., 1., 1.])



tensor([0., 0., 1.])


In [29]:
# 求不reduced max
y, indices = torch.max(x, 0)
y.backward()
print(x.grad)
# tensor([1., 0., 0.])

tensor([0., 0., 2.])
